mod_name = "World Foundry"
mod_id = "world_foundry"
mod_group = "org.teamvoided"
mod_version = "2.0.0-alpha.1"
mod_description = "Adds a new world type to the create world screen."
github_repo = "TeamVoided/WorldFoundry"
discord_invite = "https://discord.gg/KZ5Q364hEg"
authors = [ "DuskAutumnStorm", "TheEnderCore" ]
license = "MIT"
min_minecraft = "1.21.11" # Inclusive
max_minecraft = "26.1" # Exclusive
